/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module auto_tester_5 (
    input clk,
    input rst,
    input restart,
    output reg [19:0] out
  );
  
  
  
  localparam CLKSPEED = 5'h1a;
  
  reg [25:0] M_counter_d, M_counter_q = 1'h0;
  
  wire [16-1:0] M_alu_s;
  wire [3-1:0] M_alu_zvn;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn_signal;
  alu_4 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn_signal(M_alu_alufn_signal),
    .s(M_alu_s),
    .zvn(M_alu_zvn)
  );
  
  localparam START_state = 5'd0;
  localparam ADD_state = 5'd1;
  localparam SUB_state = 5'd2;
  localparam MULTIPLY_state = 5'd3;
  localparam AND_state = 5'd4;
  localparam NAND_state = 5'd5;
  localparam OR_state = 5'd6;
  localparam NOR_state = 5'd7;
  localparam XOR_state = 5'd8;
  localparam XNOR_state = 5'd9;
  localparam A_state = 5'd10;
  localparam SHL_state = 5'd11;
  localparam SHR_state = 5'd12;
  localparam SRA_state = 5'd13;
  localparam CMPEQ_state = 5'd14;
  localparam CMPLT_state = 5'd15;
  localparam CMPLE_state = 5'd16;
  localparam END_state = 5'd17;
  localparam ERROR_state = 5'd18;
  
  reg [4:0] M_state_d, M_state_q = START_state;
  
  always @* begin
    M_state_d = M_state_q;
    M_counter_d = M_counter_q;
    
    M_counter_d = M_counter_q + 1'h1;
    
    case (M_state_q)
      START_state: begin
        M_alu_alufn_signal = 1'h0;
        out = 20'h00000;
        M_alu_a = 16'h0000;
        M_alu_b = 16'h0000;
        if (restart == 1'h1) begin
          M_state_d = ADD_state;
        end
      end
      ADD_state: begin
        M_alu_alufn_signal = 6'h00;
        M_alu_a = 16'h0001;
        M_alu_b = 16'h0001;
        if (M_alu_s == 16'h0002) begin
          out = 20'h5b9de;
          M_state_d = SUB_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      SUB_state: begin
        M_alu_alufn_signal = 6'h01;
        M_alu_a = 16'h0007;
        M_alu_b = 16'h0005;
        if (M_alu_s == 16'h0002) begin
          out = 20'h2c29e;
          M_state_d = MULTIPLY_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      MULTIPLY_state: begin
        M_alu_alufn_signal = 6'h02;
        M_alu_a = 16'h000f;
        M_alu_b = 16'h0003;
        if (M_alu_s == 16'h002d) begin
          out = 20'h7be0d;
          M_state_d = AND_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      AND_state: begin
        M_alu_alufn_signal = 6'h18;
        M_alu_a = 16'h016d;
        M_alu_b = 16'h006c;
        if (M_alu_s == 16'h006c) begin
          out = 20'h5bdde;
          M_state_d = NAND_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      NAND_state: begin
        M_alu_alufn_signal = 6'h19;
        M_alu_a = 16'hff00;
        M_alu_b = 16'hf0f0;
        if (M_alu_s == 16'h0fff) begin
          out = 20'h7adee;
          M_state_d = OR_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      OR_state: begin
        M_alu_alufn_signal = 6'h1e;
        M_alu_a = 16'h00cc;
        M_alu_b = 16'h0303;
        if (M_alu_s == 16'h03cf) begin
          out = 20'h04bde;
          M_state_d = NOR_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      NOR_state: begin
        M_alu_alufn_signal = 6'h1f;
        M_alu_a = 16'h000f;
        M_alu_b = 16'h00c3;
        if (M_alu_s == 16'hff30) begin
          out = 20'h7825e;
          M_state_d = XOR_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      XOR_state: begin
        M_alu_alufn_signal = 6'h16;
        M_alu_a = 16'h003f;
        M_alu_b = 16'h003f;
        if (M_alu_s == 16'h0000) begin
          out = 20'h9825e;
          M_state_d = XNOR_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      XNOR_state: begin
        M_alu_alufn_signal = 6'h17;
        M_alu_a = 16'h002a;
        M_alu_b = 16'h002c;
        if (M_alu_s == 16'hfff9) begin
          out = 20'h9bc12;
          M_state_d = A_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      A_state: begin
        M_alu_alufn_signal = 6'h1a;
        M_alu_a = 16'h002a;
        M_alu_b = 16'h002c;
        if (M_alu_s == 16'h002a) begin
          out = 20'h5fbde;
          M_state_d = SHL_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      SHL_state: begin
        M_alu_alufn_signal = 6'h20;
        M_alu_a = 16'h0001;
        M_alu_b = 16'h0002;
        if (M_alu_s == 16'h0004) begin
          out = 20'h2cdbe;
          M_state_d = SHR_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      SHR_state: begin
        M_alu_alufn_signal = 6'h21;
        M_alu_a = 16'h8000;
        M_alu_b = 16'h0001;
        if (M_alu_s == 16'h4000) begin
          out = 20'h2ce5e;
          M_state_d = SRA_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      SRA_state: begin
        M_alu_alufn_signal = 6'h23;
        M_alu_a = 16'h8000;
        M_alu_b = 16'h0001;
        if (M_alu_s == 16'hc000) begin
          out = 20'h2c97e;
          M_state_d = CMPEQ_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      CMPEQ_state: begin
        M_alu_alufn_signal = 6'h33;
        M_alu_a = 16'h1111;
        M_alu_b = 16'h1111;
        if (M_alu_s == 16'h0001) begin
          out = 20'hac53e;
          M_state_d = CMPLT_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      CMPLT_state: begin
        M_alu_alufn_signal = 6'h35;
        M_alu_a = 16'h0111;
        M_alu_b = 16'h1111;
        if (M_alu_s == 16'h0001) begin
          out = 20'hac7de;
          M_state_d = CMPLE_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      CMPLE_state: begin
        M_alu_alufn_signal = 6'h37;
        M_alu_a = 16'h0111;
        M_alu_b = 16'h1111;
        if (M_alu_s == 16'h0001) begin
          out = 20'hab63e;
          M_state_d = END_state;
        end else begin
          out = 20'h8ca5e;
          M_state_d = ERROR_state;
        end
      end
      END_state: begin
        out = 20'h8bdde;
        M_alu_a = 1'h0;
        M_alu_b = 1'h0;
        M_alu_alufn_signal = 1'h0;
        if (restart == 1'h1) begin
          M_state_d = START_state;
        end
      end
      ERROR_state: begin
        M_alu_a = 1'h0;
        M_alu_b = 1'h0;
        M_alu_alufn_signal = 1'h0;
        out = 20'h8ca5e;
        if (restart == 1'h1) begin
          M_state_d = START_state;
        end
      end
      default: begin
        M_state_d = START_state;
        out = 20'hf7bde;
        M_alu_a = 1'h0;
        M_alu_b = 1'h0;
        M_alu_alufn_signal = 1'h0;
      end
    endcase
  end
  
  always @(posedge M_counter_q[25+0-:1]) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
